### ISSUE TITLE
Example code: name xrange is not defined

### ISSUE THREAD

**Issue by nanderspeerstra** [tensorflow/tensor2tensor#278] opened 2017-09-04 13:00 UTC
When I run the following example code (the one-command version):

```
pip install tensor2tensor && t2t-trainer \
  --generate_data \
  --data_dir=~/t2t_data \
  --problems=translate_ende_wmt32k \
  --model=transformer \
  --hparams_set=transformer_base_single_gpu \
  --output_dir=~/t2t_train/base
```
I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/t2t-trainer", line 87, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/bin/t2t-trainer", line 83, in main
    schedule=FLAGS.schedule)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor/utils/trainer_utils.py", line 301, in run
    exp.train_and_evaluate()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 502, in train_and_evaluate
    self.train(delay_secs=0)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 280, in train
    hooks=self._train_monitors + extra_hooks)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 677, in _call_train
    monitors=hooks)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 296, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 458, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 956, in _train_model
    features, labels = input_fn()
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor/utils/input_fn_builder.py", line 103, in input_fn
    length_multiplier=(p_hparams.batch_size_multiplier)))
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor/utils/data_reader.py", line 457, in hparams_to_batching_scheme
    length_multiplier=length_multiplier)
  File "/usr/local/lib/python3.5/dist-packages/tensor2tensor/utils/data_reader.py", line 423, in _batching_scheme
    divisors = [i for i in xrange(1, window_size + 1) if window_size % i == 0]
NameError: name 'xrange' is not defined
```
It seems it cannot run the Python 2 command xrange, since it's Python3.

_Versions_
tensor2tensor (1.2.1)
tensorflow (1.3.0)
python (3.5)

**Comment by colmantse** [comment] 2017-09-04 13:03
Hi, can you do pip install tensor2tensor --upgrade and see if it runs again? if not I am going to reopen #265 .

**Comment by nanderspeerstra** [comment] 2017-09-04 13:10
Hi colmantse,

After running the --upgrade command, it updated the following:

```Successfully installed certifi-2017.7.27.1 chardet-3.0.4 idna-2.6 requests-2.18.4 urllib3-1.22```

So tensor2tensor is not part of it (already up-to-date). I'm now re-running my code to see if any of these packages solves it, but that seems unlikely.

I'll update here when my code is done running!

**Comment by colmantse** [comment] 2017-09-04 13:12
thanks, please see #265 for custom hack if it doesn't run tho, maybe the recent merge is not included in 1.2.1.

**Comment by nanderspeerstra** [comment] 2017-09-04 13:53
The issue is still there (xrange is not defined). I'll use the hack for now. Thanks for the quick responses!

**Comment by colmantse** [comment] 2017-09-04 13:55
n.p.

**Comment by ghego** [comment] 2017-09-11 21:25
Yep, changes were made after 1.2.1 was published. If you check out from master it should work.

**Comment by cidrugHug8** [comment] 2017-09-15 05:24
The issue is still alive in tensor2tensor 1.2.2.

**Comment by colmantse** [comment] 2017-09-15 05:26
yes there is a pr merged already, after 1.2.2, for quick fix, just do xrange--> range (i.e. remove x)

**Comment by cidrugHug8** [comment] 2017-09-15 05:30
Thank you.

**Comment by colmantse** [comment] 2017-10-02 03:01
i think this problem no longer occurs at 1.2.4? could consider closing?

**Closed** 2017-11-14 00:32 UTC
