### ISSUE TITLE
Precompiled binaries are Unix-only, no Win32 version exists

### ISSUE THREAD

**Issue by dstruct2k** [tensorflow/tensor2tensor#7] opened 2017-06-21 00:12 UTC

**Comment by rsepassi** [comment] 2017-06-23 00:47
(sorry for the open/close - bad click)

I'm looking into how to distribute a version that works on Win32. Just to be clear, `pip install tensor2tensor` works and library usage is fine, it's just `t2t-trainer` and `t2t-datagen` that don't install correctly?

**Comment by dstruct2k** [comment] 2017-06-23 00:58
Correct, from as far as I can tell. I'm not able to follow too far into even the first example given in the documentation, but `pip install tensor2tensor` _seems_ to set the environment up correctly at least.
I'm new to a lot of this and intend on learning as I go, but I don't want to have to use a VM because I'm pretty sure I'd lose CUDA.

**Comment by rsepassi** [comment] 2017-06-24 01:39
Please try running these commands and copy in the output:

```
pip install tensor2tensor[tensorflow_gpu]
python -c "from tensor2tensor.models import transformer; print(transformer.Transformer.__name__)"
t2t-datagen
t2t-trainer --registry_help
```

**Comment by dstruct2k** [comment] 2017-06-24 01:50
`pip` ran fine, but the script snippet fails to run: 
> C:\Python>python -c "from tensor2tensor.models import transformer; print(transformer.Transformer.__name__)"
> 
> Traceback (most recent call last):
>   File "C:\Python\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
>     return importlib.import_module(mname)
>   File "C:\Python\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 978, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 560, in module_from_spec
>   File "<frozen importlib._bootstrap_external>", line 922, in create_module
>   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
> ImportError: DLL load failed: The specified module could not be found.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Python\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Python\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
>     return importlib.import_module('_pywrap_tensorflow_internal')
>   File "C:\Python\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Python\lib\site-packages\tensor2tensor\models\transformer.py", line 31, in <module>
>     from tensor2tensor.models import common_attention
>   File "C:\Python\lib\site-packages\tensor2tensor\models\common_attention.py", line 24, in <module>
>     from tensor2tensor.models import common_layers
>   File "C:\Python\lib\site-packages\tensor2tensor\models\common_layers.py", line 26, in <module>
>     from tensor2tensor.utils import expert_utils as eu
>   File "C:\Python\lib\site-packages\tensor2tensor\utils\expert_utils.py", line 32, in <module>
>     import tensorflow as tf
>   File "C:\Python\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
>     from tensorflow.python import *
>   File "C:\Python\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "C:\Python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 52, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "C:\Python\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
>     return importlib.import_module(mname)
>   File "C:\Python\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 978, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 560, in module_from_spec
>   File "<frozen importlib._bootstrap_external>", line 922, in create_module
>   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
> ImportError: DLL load failed: The specified module could not be found.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Python\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Python\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
>     return importlib.import_module('_pywrap_tensorflow_internal')
>   File "C:\Python\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'
> 
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/install_sources#common_installation_problems
> 
> for some common reasons and solutions.  Include the entire stack trace
> above this error message when asking for help.
> 
> C:\Python>

`t2t-datagen` and `t2t-trainer` "aren't recognized as an internal or external command, operable program or batch file."

**Comment by rsepassi** [comment] 2017-06-26 20:37
It seems your issue may be addressed here: https://stackoverflow.com/questions/42011070/on-windows-running-import-tensorflow-generates-no-module-named-pywrap-tenso

Please make sure tensorflow works on its own.

**Comment by lukaszkaiser** [comment] 2017-06-27 03:21
Is this solved with the above instructions? I'm closing for now, please reopen if the problem is still there.

**Closed by lukaszkaiser** 2017-06-27 03:21 UTC

**Comment by colmantse** [comment] 2017-07-17 15:15
I followed the 4 lines, the first 2 works, output name --> Transformer
the 3rd line gives t2t-datagen is not recognized as an internal or external command... 
same with 4th line.

So i guess the problem is still here? I am on window 64 bit python3 tensorflow-gpu env
