### ISSUE TITLE
"Invalid argument: slice index 1 of dimension 1 out of bounds." Error when decoding the text to Class_Label using Transformer model

### ISSUE THREAD

**Issue by yynil** [tensorflow/tensor2tensor#43] opened 2017-06-25 02:44 UTC
Hi, 
    I add a dataset to do the classification using the Transformer model. I generated the dataset successfully and trained the model successfully. But when I do the decoding, the invalid argument error is thrown.
   The following codes are used to generate dataset, it's simply to pick up data from several dataset and make the combinations. Each combination is a category. The task is to find out which category is for a new set of data.
   For an example, there are four dataset: A,B,C,D. They have several members like:
   A: a0,a1,a2
   B: b0,b1,b2,b3
   C: c0,c1
   D: d0,d1,d2
   So there will be 15 combinations(aka. categories): A,B,C,D,AB,AC,AD,BC,BD,CD,ABC,ABD,ACD,BCD,ABCD. My generator will generate random number of sequences that picks members from set A,B,C,D and generate targets label between the 0 to 15. 
    All data generation and training worked well. But when I tried to do the decoding, The invalid argument error is thrown. This error is too unspecific and I have no idea how to solve it. 
   Please be kind to review my code what's wrong in it. Thanks a lot!
   Generator:
This generator is to pick up members from several files and the file name is the single set name and assign a target classification label to it.
    
```
import numpy as np
import os, sys

from tensor2tensor.data_generators import generator_utils
from tensor2tensor.data_generators import text_encoder
from six.moves import xrange 
import ssl
import itertools	

def generateDicts(dataDir,nameFiles,idFrom=100):
	dictFileName=dataDir+"/name.dict"
	categories=len(nameFiles)
	nameset=dict()
	for name in nameFiles:
		nameFile=open(dataDir+"/"+name)
		names=list()
		for individual in nameFile:
			names.append(individual.strip())
		nameset[name]=names
		nameFile.close()
	allNames=set()
	for (k,v) in zip(nameset.keys(),nameset.values()) :
		allNames=allNames.union(set(v))
		print("lenOfAllNames after add "+k+" is "+str(len(allNames)))
	allNamesList=sorted(allNames)
	names=dict()
	idx=idFrom+1
	for name in allNamesList:
		names[idx]=name
		idx+=1
	dictFile=open(dictFileName,"w")
	for (k,v) in zip(names.keys(),names.values()):
		dictFile.write(v+"\n")
	dictFile.close()

	combos=dict()

	for i in xrange(len(nameFiles)):
		combination=itertools.combinations(nameFiles,i+1)
		for signleComb in combination:
			combos["_".join(signleComb)]=i
	return nameset,names,combos

def generateCase(nameset,names,nameFiles,combos,maxMembers):
	categories=len(nameFiles)
	categorySize=list()
	members = np.random.randint(maxMembers)+1
	leftMembers = members
	categoryList=list()
	inputs=list()

	for i in xrange(categories-1):
		categorySize.append(np.random.randint(leftMembers))
		leftMembers-=categorySize[i]
		if categorySize[i] != 0:
			categoryList.append(nameFiles[i])
			names=nameset[nameFiles[i]]
			nameLen=len(names)
			for j in xrange(categorySize[i]):
				nameIndex=np.random.randint(nameLen)
				inputs.append(names[nameIndex])

	i+=1
	if leftMembers != 0:
		categoryList.append(nameFiles[i])
		names=nameset[nameFiles[i]]
		nameLen=len(names)
		for j in xrange(leftMembers):
			nameIndex=np.random.randint(nameLen)
			inputs.append(names[nameIndex])

	cateStr="_".join(categoryList)
	outputs=[cateStr]
	return inputs,outputs

def party_party_generator(dataDir,nameFiles,maxMembers,numOfCases):
	nameset,names,combos=generateDicts(dataDir,nameFiles)
	#targetDict=dataDir+"/targets.dict"
	#targetDictFile=open(targetDict,"w")
	#for combo in combos:
	#	targetDictFile.write(combo+"\n")
	#targetDictFile.close()
	dictFileName=dataDir+"/name.dict"
	inputsTextToken=text_encoder.TokenTextEncoder(dictFileName)
	#targetsTextToken=text_encoder.TokenTextEncoder(targetDict)

	for i in xrange(numOfCases):
		inputs,outputs=generateCase(nameset,names,nameFiles,combos,maxMembers)
		strInput=" ".join(inputs)
		encodedInputs=inputsTextToken.encode(strInput)
		np.random.shuffle(encodedInputs)
		encodedOutputs=[combos[outputs[0]]]
		yield {"inputs":encodedInputs,"targets":encodedOutputs}
```

HParams I added 
I feel a little bit confused about the input_space_id and target_space_id, it seems like I can set anything to it without any problems.

```
def party_party(model_hparams):
  """Party Party."""
  p = default_problem_hparams()
  nameDict=model_hparams.data_dir+"/name.dict"
  targetDict=model_hparams.data_dir+"/targets.dict"
  num_lines = sum(1 for line in open(nameDict))
  target_lines= sum(1 for line in open(targetDict))
  p.input_modality = {"inputs": (registry.Modalities.SYMBOL, num_lines)}
  p.vocabulary = {
    "inputs": text_encoder.TokenTextEncoder(vocab_filename=nameDict),
	  "targets": text_encoder.TextEncoder(),
  }
  p.target_modality = (registry.Modalities.CLASS_LABEL, target_lines)
  p.batch_size_multiplier = 4
  p.max_expected_batch_size_per_shard = 8
  p.loss_multiplier = 3.0
  p.input_space_id = 1
  p.target_space_id = 1
  return p
```

`"party_party": lambda p:party_party(p),`

The training script I am using:
Since I need to change the t2t codes frequently, I don't install it to my site-package directory.

`tensor2tensor/bin/t2t-trainer --data_dir /mnt/5efa3937-4221-48b5-9660-85a4a7eb0cfd/data/ --problems=party_party --model=transformer --hparams_set=transformer_base_single_gpu --keep_checkpoint_max=5 --save_checkpoints_secs=3600 --hparams='batch_size=2048' --output_dir /mnt/5efa3937-4221-48b5-9660-85a4a7eb0cfd/model`

The predict script I'm using:
```

# Decode
DATA_DIR=/mnt/5efa3937-4221-48b5-9660-85a4a7eb0cfd/data
PROBLEM=party_party
MODEL=transformer
DECODE_FILE=decode.txt
TRAIN_DIR=/mnt/5efa3937-4221-48b5-9660-85a4a7eb0cfd/model
HPARAMS=transformer_base_single_gpu
BEAM_SIZE=4
ALPHA=0.6

tensor2tensor/bin/t2t-trainer \
  --data_dir=$DATA_DIR \
  --problems=$PROBLEM \
  --model=$MODEL \
  --hparams_set=$HPARAMS \
  --output_dir=$TRAIN_DIR \
  --train_steps=0 \
  --eval_steps=0 \
  --decode_beam_size=$BEAM_SIZE \
  --decode_alpha=$ALPHA \
  --decode_from_file=$DECODE_FILE
```

The decode.txt is pretty simple:

> 324 f2r32f2r5 3f2fsfda fewfoIFE fselfj203 fselfj203 fj203rf2 3jr22iofj dsfslfkj23LJ dsf2f dsfslfkj23LJ dsflw2mf>K

This text will be encoded to int ids just like what the generator does.

However  this text is random generated, the procedure is very common to classify the text corpus.
Please help to see where I made wrong. Thanks a lot!

**Comment by lukaszkaiser** [comment] 2017-06-25 03:32
I can confirm that I see this problem with other models too. Investigating...

**Comment by yynil** [comment] 2017-06-27 07:41
@lukaszkaiser I just traced the codes to 
tensor2tensor/utils/t2t_model.py in symbols_to_logits_fn
logits = logits[:, current_output_position, :, :]
it seems like current_output_position is wrong when the Modality is Class_Label modality.

**Comment by yynil** [comment] 2017-06-27 16:16
@lukaszkaiser 
A little big more digging:
since problem occurs when slicing logits tensor, I noticed that there was a flag to disable it.
in the file: tensor2tensor/utils/t2t_model.py
def _beam_decode(self, features, decode_length, beam_size, top_beams,
                   last_position_only, alpha):
the last_position_only can disable the logits slicing.
i just added one line below the definition.
last_position_only=True

The search can continue to work while unable to make good predictions.

I'm not sure if there is anything wrong in model or in the beam_search implementation or in tensorflow 1.2.

Thanks a lot!

**Comment by lukaszkaiser** [comment] 2017-06-30 01:02
I hope this is corrected in 1.0.9. Closing for now, but please reopen if you see the problem!

**Closed by lukaszkaiser** 2017-06-30 01:02 UTC

**Comment by alcaster** [comment] 2017-07-13 06:39
Hi. I added a simple new fully connected model.
`    def fully_connected_model(self, inputs):
        with tf.variable_scope("fully_connected_model"):
            out_shape = inputs.get_shape().as_list()[-1]
            fc1 = layers.fully_connected(inputs=inputs, num_outputs=out_shape, activation_fn=tf.nn.relu, scope='fc1')
            tf.summary.histogram('fc1', fc1)
            tf.summary.histogram('fc1/sparsity', tf.nn.zero_fraction(fc1))

            fc2 = layers.fully_connected(inputs=fc1, num_outputs=int(1.8 * out_shape), activation_fn=tf.nn.relu,
                                         scope='fc2')
            tf.summary.histogram('fc2', fc2)
            tf.summary.histogram('fc2/sparsity', tf.nn.zero_fraction(fc2))

            out_shape = layers.fully_connected(fc2, out_shape, scope='out')
            return out_shape`
Model can be trained but when decoding this error described here happens.
The trick of omitting beam search by last_position_only=True works but it's not a solution.

`InvalidArgumentError (see above for traceback): slice index 25 of dimension 1 out of bounds.
         [[Node: while/strided_slice_3 = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=13, ellipsis_mask=0, end_mask=13, new_axis_mask=0, shrink_axis_mask=2, _device="/job:localhost/replica:0/task:0/cpu:0"](while/symbol_modality_7995_64_2/parallel_0/symbol_modality_7995_64/softmax/ExpandDims, while/strided_slice_3/stack, while/strided_slice_3/stack_1, while/strided_slice_3/stack_2)]]`
I'm using basic_1 hparams and decode_beam_size=4, decode_alpha=0.6

**Comment by yynil** [comment] 2017-07-13 06:49
just set teh beam_size to 1 and use the greedy_search instead of beam search.

**Comment by alcaster** [comment] 2017-07-13 09:25
Unfortunately the problem still occurs.

**Comment by alcaster** [comment] 2017-07-17 08:26
~~~
INFO:tensorflow:Restoring parameters from /home/xxx/fully1/model.ckpt-1
2017-07-17 10:20:37.150523: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: slice index 25 of dimension 1 out of bounds.
Traceback (most recent call last):
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1139, in _do_call
    return fn(*args)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1121, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 25 of dimension 1 out of bounds.
         [[Node: foldl/while/strided_slice_1 = StridedSlice[Index=DT_INT32, T=DT_INT64, begin_mask=13, ellipsis_mask=0, end_mask=13, new_axis_mask=0, shrink_axis_mask=2, _device="/job:localhost/replica:0/task:0/cpu:0"](foldl/while/concat/_395, foldl/while/strided_slice_1/stack/_397, foldl/while/strided_slice_1/stack_1/_399, foldl/while/strided_slice_1/stack_2/_401)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxx/anlg/bin/../3rdParty/tensor2tensor//tensor2tensor/bin/t2t-trainer", line 85, in <module>
    tf.app.run()
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/xxx/anlg/bin/../3rdParty/tensor2tensor//tensor2tensor/bin/t2t-trainer", line 81, in main
    schedule=FLAGS.schedule)
  File "/home/xxx/anlg/3rdParty/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 247, in run
    run_locally(exp_fn(output_dir))
  File "/home/xxx/anlg/3rdParty/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 547, in run_locally
    decode_from_file(estimator, FLAGS.decode_from_file)
  File "/home/xxx/anlg/3rdParty/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 652, in decode_from_file
    for result in result_iter:
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 902, in _predict_generator
    preds = mon_sess.run(predictions, feed_fn() if feed_fn else None)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 505, in run
    run_metadata=run_metadata)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 842, in run
    run_metadata=run_metadata)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 798, in run
    return self._sess.run(*args, **kwargs)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 952, in run
    run_metadata=run_metadata)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 798, in run
    return self._sess.run(*args, **kwargs)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 25 of dimension 1 out of bounds.
         [[Node: foldl/while/strided_slice_1 = StridedSlice[Index=DT_INT32, T=DT_INT64, begin_mask=13, ellipsis_mask=0, end_mask=13, new_axis_mask=0, shrink_axis_mask=2, _device="/job:localhost/replica:0/task:0/cpu:0"](foldl/while/concat/_395, foldl/while/strided_slice_1/stack/_397, foldl/while/strided_slice_1/stack_1/_399, foldl/while/strided_slice_1/stack_2/_401)]]

Caused by op 'foldl/while/strided_slice_1', defined at:
  File "/home/xxx/anlg/bin/../3rdParty/tensor2tensor//tensor2tensor/bin/t2t-trainer", line 85, in <module>
    tf.app.run()
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/xxx/anlg/bin/../3rdParty/tensor2tensor//tensor2tensor/bin/t2t-trainer", line 81, in main
    schedule=FLAGS.schedule)
  File "/home/xxx/anlg/3rdParty/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 247, in run
    run_locally(exp_fn(output_dir))
  File "/home/xxx/anlg/3rdParty/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 547, in run_locally
    decode_from_file(estimator, FLAGS.decode_from_file)
  File "/home/xxx/anlg/3rdParty/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 651, in decode_from_file
    as_iterable=True)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 289, in new_func
    return func(*args, **kwargs)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 590, in predict
    as_iterable=as_iterable)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 884, in _infer_model
    infer_ops = self._get_predict_ops(features)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1218, in _get_predict_ops
    return self._call_model_fn(features, labels, model_fn_lib.ModeKeys.INFER)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1133, in _call_model_fn
    model_fn_results = self._model_fn(features, labels, **kwargs)
  File "/home/xxx/anlg/3rdParty/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 432, in model_fn
    len(hparams.problems) - 1)
  File "/home/xxx/anlg/3rdParty/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 754, in _cond_on_index
    return fn(cur_idx)
  File "/home/xxx/anlg/3rdParty/tensor2tensor/tensor2tensor/utils/trainer_utils.py", line 404, in nth_model
    decode_length=FLAGS.decode_extra_length)
  File "/home/xxx/anlg/3rdParty/tensor2tensor/tensor2tensor/utils/t2t_model.py", line 173, in infer
    return self._greedy_infer(features, decode_length, last_position_only)
  File "/home/xxx/anlg/3rdParty/tensor2tensor/tensor2tensor/utils/t2t_model.py", line 312, in _greedy_infer
    parallel_iterations=1)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/ops/functional_ops.py", line 122, in foldl
    swap_memory=swap_memory)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2770, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2599, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2549, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/ops/functional_ops.py", line 116, in compute
    a = fn(a, elems_ta.read(i))
  File "/home/xxx/anlg/3rdParty/tensor2tensor/tensor2tensor/utils/t2t_model.py", line 285, in infer_step
    cur_sample = samples[:, tf.shape(recent_output)[1], :, :]
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 499, in _SliceHelper
    name=name)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 663, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3515, in strided_slice
    shrink_axis_mask=shrink_axis_mask, name=name)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/xxx/.vir/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): slice index 25 of dimension 1 out of bounds.
         [[Node: foldl/while/strided_slice_1 = StridedSlice[Index=DT_INT32, T=DT_INT64, begin_mask=13, ellipsis_mask=0, end_mask=13, new_axis_mask=0, shrink_axis_mask=2, _device="/job:localhost/replica:0/task:0/cpu:0"](foldl/while/concat/_395, foldl/while/strided_slice_1/stack/_397, foldl/while/strided_slice_1/stack_1/_399, foldl/while/strided_slice_1/stack_2/_401)]]
~~~
