### ISSUE TITLE
Is there a way to know the exact BPE components each word is decomposed into?

### ISSUE THREAD

**Issue by anglil** [tensorflow/tensor2tensor#408] opened 2017-11-09 23:35 UTC
For example, if the word "learning" is decomposed into "le", "arn", "ing", is it possible to know so?

**Comment by colmantse** [comment] 2017-11-10 05:47
do you mean subword implementation or bpe? because I am not aware of a bpe implementation at t2t. Normally, with bpe you would have a bpe-model that segregate words into wordpieces, so you can check by requesting bpe to break the word down, it could be 'learning' to.

**Comment by martinpopel** [comment] 2017-11-13 13:12
There is a [subword implementation](https://github.com/tensorflow/tensor2tensor/blob/75b75f2e2281101b9b3637e14ef519afd6a11b68/tensor2tensor/data_generators/text_encoder.py#L383-L414) in T2T, which is very similar to BPE. There is also a wrapper script [text_encoder_build_subword.py](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/text_encoder_build_subword.py), which can be used to train the subword vocabulary separately (either from a corpus or from a word vocabulary). 

When training e.g. `translate_ende_wmt32k`, the subword vocabulary is stored in `~/t2t_data/vocab.ende.32768` and it is a plain text file and on line 4496 I can see `'learning_'`, which means that this word (followed by a space) is represented as one subword in this case. However, if "learning" was not followed by a space, but a comma, there is no such entry in the vocabulary, so I guess it will have to be divided as `lear + ning + ,_` because the vocabulary contains the following relevant entries in this order: `,_ ing ni ng ar le rn ear lea in ea nin arn earn ning lear`.

However, I am not aware of a simple way how to check this, i.e. to apply a trained subword vocab to a given string.

Related questions: How to know in T2T how many subwords are in my training data? And how to convert a number of training steps to a number of epochs (passes over the training data).

**Comment by twairball** [comment] 2017-11-13 16:05
You can test this by encoding the string with your vocab file:

````
vocab = text_encoder.SubwordTextEncoder(vocab_filepath)
encodings = vocab.encode("learning")
print(encodings)
````

**Comment by martinpopel** [comment] 2017-11-13 16:49
@twairball Thanks for a hint (I was sure it is possible, but I just have not tried it yet.)
Your code does not work as intended because _subtoken_ids_to_tokens concatenates all the subwords without any delimiter.
We need to use e.g.
``` python
from tensor2tensor.data_generators import text_encoder
vocab = text_encoder.SubwordTextEncoder(vocab_filepath)
print([vocab._subtoken_ids_to_tokens([x]) for x in vocab.encode("learnings")])
```
which prints `[['lear'], ['ning'], ['s']]`.

So I think @anglil can close this issue. I have opened another issue #415 for the number of epochs.

BTW: my guess with "learnings" followed by a comma was wrong. The underscore does not mean a space:
```python
>>> print([vocab._subtoken_ids_to_tokens([x]) for x in vocab.encode("learning,")])
[['learning'], [',']]
>>> print([vocab._subtoken_ids_to_tokens([x]) for x in vocab.encode("learning ,")])
[['learning'], [' ,']]
```

**Comment by rsepassi** [comment] 2017-11-13 21:34
Closing as these answers seem sufficient. Thank you @twairball, @martinpopel, and @colmantse!

**Closed by rsepassi** 2017-11-13 21:34 UTC

**Comment by yuimo** [comment] 2017-11-24 03:46
hi all, when i run the test code of t2t such as "python  /anaconda2/lib/python2.7/site-packages/tensor2tensor/data_generators/translate_test.py"

it report some errors like:
do you know the reason?
thanks a lot.


yuanhao:site-packages higgs$ python tensor2tensor/data_generators/translate_test.py
Traceback (most recent call last):
  File "tensor2tensor/data_generators/translate_test.py", line 29, in <module>
    from tensor2tensor.data_generators import text_encoder
  File "/anaconda2/lib/python2.7/site-packages/tensor2tensor/data_generators/text_encoder.py", line 36, in <module>
    from tensor2tensor.data_generators import tokenizer
  File "/anaconda2/lib/python2.7/site-packages/tensor2tensor/data_generators/tokenizer.py", line 55, in <module>
    import tensorflow as tf
  File "/anaconda2/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/anaconda2/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *
  File "/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/framework_lib.py", line 76, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 39, in <module>
    from tensorflow.python.framework import errors
  File "/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/errors.py", line 22, in <module>
    from tensorflow.python.framework import errors_impl as _impl
  File "/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 27, in <module>
    from tensorflow.python.util import compat
  File "/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/compat.py", line 43, in <module>
    from tensorflow.python.util.all_util import remove_undocumented
  File "/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/all_util.py", line 24, in <module>
    from tensorflow.python.util import tf_inspect as _tf_inspect
  File "/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/tf_inspect.py", line 20, in <module>
    import inspect as _inspect
  File "/anaconda2/lib/python2.7/site-packages/tensor2tensor/data_generators/inspect.py", line 31, in <module>
    from tensor2tensor.data_generators import text_encoder
ImportError: cannot import name text_encoder
