### ISSUE TITLE
beam_score value changes based on batch size and composition

### ISSUE THREAD

**Issue by katelynrwalker** [tensorflow/tensor2tensor#1756] opened 2019-11-26 18:44 UTC
I'm getting some strange behavior when I output beam scores from the decoder using 
`--decode_hparams="beam_size=1, return_beams=True, write_beam_scores=True, extra_length=0, force_decode_length=True"`
The beam_score that is written for a single sample changes depending on the batch size and overall number of samples (I'm presuming that second part means that the beam_score changes depending on what other items are in a particular batch, since batches are shuffled to put similar-length inputs together). The output for the sample will be the same, but the beam score changes. Any ideas what might be going on here?

Examples (the score given is for a the same individual sample in each case. The decoded output is the same each time, but the score is different):

108000 samples (batch size =64) 	-50.76

100 samples (batch size =64) 	-62.59

10 samples (batch size =64)  	-52.70

1000 samples (batch size =32) 	-51.25

100 samples (batch size =32) 	-45.02

1 sample (batch size =1 or 64) 	-34.40

**Comment by real-brilliant** [comment] 2019-11-27 09:20
i'm not sure whether it's the fault of `stop_early`
could you try that again when `stop_early=False`?

**Comment by martinpopel** [comment] 2019-12-02 17:18
> batches are shuffled to put similar-length inputs together

Yes, but there will be still differences in sentence lengths. It depends on the test set size and length variability.

I think the difference in scores are caused by the length of the longest sentence in a batch.
You can test this hypothesis by creating a dummy test set with the same sentence repeated 64 times and re-running the experiments.

**Comment by katelynrwalker** [comment] 2019-12-04 00:17
You're right, @martinpopel - running batches of any size with the same sentence repeated over and over returns the same score regardless of number of samples in the batch. Adding different shorter sentences also returns the same score for the original (longest) sentence. Adding different longer sentences changes the score for that original sentence. At least now I understand what's happening, even if I don't know how to fix it yet! Thank you.

@real-brilliant changing stop_early to False in beam_search.py didn't make any difference in the output scores. Though there may be somewhere else in the code that changes it to True during the decode process. `stop_early` isn't a valid flag for t2t-decoder so I'm not totally sure how you're suggesting I change it.

**Comment by real-brilliant** [comment] 2019-12-04 02:50
@katelynrwalker Decoding process will be stopped if no alive beam better than finished beam when `stop_early=True`. However, there's a bug before and batch_decoding will be stopped as long as there's a snt be stopped, and i'm not sure whether the bug has been fixed in your vision.

As for max_snt_len may influence scores, sorry for mistaking beam score for bleu score. beam score is calculated by len_penalty and summed_log_probs, and decoding will not stop unless all snt reach <EOS>

**Closed** 2020-01-29 22:31 UTC
