### ISSUE TITLE
Tensorflow TypeError

### ISSUE THREAD

**Issue by grafael** [tensorflow/tensor2tensor#273] opened 2017-09-01 19:14 UTC
What version of tensorflow tensor2tensor require?

I'm using the **tensorflow-gpu** version **1.2.1**

I just run:
```shell
pip install tensor2tensor && t2t-trainer \
  --generate_data \
  --data_dir=~/t2t_data \
  --problems=translate_ende_wmt32k \
  --model=transformer \
  --hparams_set=transformer_base_single_gpu \
  --output_dir=~/t2t_train/base
```

I got the **error**:

```shell
INFO:tensorflow:Performing local training and evaluation.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/monitors.py:268: __
init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.
INFO:tensorflow:batching_scheme = {'boundaries': [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 24, 26, 28, 30,
33, 36, 39, 42, 46, 50, 55, 60, 66, 72, 79, 86, 94, 103, 113, 124, 136, 149, 163, 179, 196, 215, 236], 'window_size': 72
0, 'max_length': 256, 'batch_sizes': [240, 180, 180, 180, 144, 144, 144, 120, 120, 120, 90, 90, 90, 90, 80, 72, 72, 60,
60, 48, 48, 48, 40, 40, 36, 30, 30, 24, 24, 20, 20, 18, 18, 16, 15, 12, 12, 10, 10, 9, 8, 8], 'shuffle_queue_size': 270}
Traceback (most recent call last):
  File "/usr/local/bin/t2t-trainer", line 87, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/bin/t2t-trainer", line 83, in main
    schedule=FLAGS.schedule)
  File "/usr/local/lib/python2.7/dist-packages/tensor2tensor/utils/trainer_utils.py", line 301, in run
    exp.train_and_evaluate()
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/function.py", line 619, in add_to_graph
    self._create_definition_if_needed()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/data/python/framework/function.py", line 167, in _create_definition_if_needed
    outputs = self._func(*inputs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/data/python/ops/dataset_ops.py", line 1427, in tf_map_func
    flattened_ret = [ops.convert_to_tensor(t) for t in nest.flatten(ret)]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 676, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 741, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 462, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <type 'dict'> to Tensor. Contents: {'inputs': <tf.Tensor 'SparseToDense:0' shape=(?,) dtype=int64>, 'targets': <tf.Tensor 'SparseToDense_1:0' shape=(?,) dtype=int64>}. Consider casting elements to a supported type.
```

**Comment by mirkobronzi** [comment] 2017-09-01 19:49
same here - it seems more a problem where a python dict (name: tensor) is provided instead of a tensor...

(not sure it is a problem with my registered problem though - but it was working well with version 1.1.9)

**Comment by mtu** [comment] 2017-09-06 08:53
same problem with 1.2.1.  Another problem occurs with version 1.1.9.

**Comment by mehmedes** [comment] 2017-09-07 17:25
Have you tried upgrading to Tensorflow 1.3?

**Comment by mtu** [comment] 2017-09-08 03:46
I changed to another stable t2t version, now it works well with 1.2.1

**Comment by mirkobronzi** [comment] 2017-09-08 13:21
@mtu  : 
by 'I changed to another stable t2t' you mean you just updated tensor2tensor code?

**Comment by mtu** [comment] 2017-09-09 06:36
@mirkobronzi changed to an earlier version,not the latest one

**Comment by lukaszkaiser** [comment] 2017-09-11 02:41
Is this resolved in T2T 1.2.2 with TF 1.3?

**Comment by David-Levinthal** [comment] 2017-09-14 19:57
I see the error with TF 1.3 built on python 2.7
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 462, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <type 'dict'> to Tensor. Contents: {'inputs': <tf.Tensor 'SparseToDense:0' shape=(?,) dtype=int64>, 'targets': <tf.Tensor 'SparseToDense_1:0' shape=(?,) dtype=int64>}. Consider casting elements to a supported type.
after invoking
levinth@c2k-144-linux:~/tensor2tensor$ t2t-trainer \
>   --data_dir=$DATA_DIR \
>   --problems=$PROBLEM \
>   --model=$MODEL \
>   --hparams_set=$HPARAMS \
>   --output_dir=$TRAIN_DIR

this worked fine
 t2t-datagen --data_dir=$DATA_DIR --tmp_dir=$TMP_DIR --problem=$PROBLEM

**Comment by threedliteguy** [comment] 2017-09-15 02:48
I get a different error:

t2t-trainer   --generate_data   --data_dir=~/t2t_data   --problems=translate_ende_wmt32k   --model=transformer   --hparams_set=transformer_base_single_gpu   --output_dir=~/t2t_train/base
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "/home/dan/.local/bin/t2t-trainer", line 38, in <module>
    from tensor2tensor.utils import trainer_utils
  File "/home/dan/.local/lib/python2.7/site-packages/tensor2tensor/utils/trainer_utils.py", line 27, in <module>
    from tensor2tensor.data_generators import all_problems  # pylint: disable=unused-import
  File "/home/dan/.local/lib/python2.7/site-packages/tensor2tensor/data_generators/all_problems.py", line 22, in <module>
    from tensor2tensor.data_generators import algorithmic
  File "/home/dan/.local/lib/python2.7/site-packages/tensor2tensor/data_generators/algorithmic.py", line 28, in <module>
    from tensor2tensor.data_generators import problem
  File "/home/dan/.local/lib/python2.7/site-packages/tensor2tensor/data_generators/problem.py", line 31, in <module>
    from tensor2tensor.utils import metrics
  File "/home/dan/.local/lib/python2.7/site-packages/tensor2tensor/utils/metrics.py", line 23, in <module>
    from tensor2tensor.layers import common_layers
  File "/home/dan/.local/lib/python2.7/site-packages/tensor2tensor/layers/common_layers.py", line 30, in <module>
    from tensor2tensor.utils import expert_utils as eu
  File "/home/dan/.local/lib/python2.7/site-packages/tensor2tensor/utils/expert_utils.py", line 398, in <module>
    initializer=tf.zeros_initializer(),
TypeError: zeros_initializer() takes at least 1 argument (0 given)

**Comment by rsepassi** [comment] 2017-10-07 20:40
I cannot reproduce this. The Travis CI tests demonstrate that the commands you seem to be running work fine. Please make sure you're running TensorFlow 1.3 and the latest version of Tensor2Tensor. 

Please provide the command line you use (without env vars - use actual values)

**Closed** 2017-10-13 00:53 UTC
