### ISSUE TITLE
when I use new version tensor2tensor 1.2.0, only use cpu instead of GPU

### ISSUE THREAD

**Issue by lqfarmer** [tensorflow/tensor2tensor#260] opened 2017-08-29 06:04 UTC
I doing ende translation problem use transfomer model. and I have 8 GPU on my machine, I used them all. 
during model building, program give imformation as follows:
**************************************************
INFO:tensorflow:Unsetting shared_embedding_and_softmax_weights.
INFO:tensorflow:Doing model_fn_body took 2.946 sec.
INFO:tensorflow:Doing model_fn_body took 1.755 sec.
INFO:tensorflow:Doing model_fn_body took 1.756 sec.
INFO:tensorflow:Doing model_fn_body took 1.876 sec.
INFO:tensorflow:Doing model_fn_body took 1.828 sec.
INFO:tensorflow:Doing model_fn_body took 1.573 sec.
INFO:tensorflow:Doing model_fn_body took 1.906 sec.
INFO:tensorflow:Doing model_fn_body took 1.711 sec.
**************************************************
but, when I see : nvidia-smi, I found no GPU used, Could you help me why ?

**Comment by rsepassi** [comment] 2017-08-29 16:36
Let's see if I can help. 

Please provide:
* the command-line you used
* the output of `pip list | grep tensor`
* the output of `nvidia-smi`

**Comment by lqfarmer** [comment] 2017-08-30 00:17
I solve it by myself, but I got anther problem when I try to run coder with transformer, 
***********************************************************************************
InvalidArgumentError (see above for traceback): Number of ways to split should evenly divide the split dimension, but got split_dim 0 (size = 1) and num_split 8
	 [[Node: split_2 = Split[T=DT_INT32, num_split=8, _device="/job:localhost/replica:0/task:0/cpu:0"](split_2/split_dim, input_reader/ExpandDims_3/_10595)]]
	 [[Node: Identity_1922/_6563 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:4", send_device="/job:localhost/replica:0/task:0/gpu:3", send_device_incarnation=1, tensor_name="edge_3341_Identity_1922", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:4"]()]]

***********************************************************************************
I set hidden size 1024, batch size 1024, training set and eval set num all can be divided evenly by 8. How doese this happened. My tensorflow version is 1.3.0, tensor2tensor is 1.2.0.

**Comment by martinpopel** [comment] 2017-09-05 12:58
I suggest to close this as a duplicate of #266.

**Comment by NickShahML** [comment] 2017-09-07 13:17
@lqfarmer can you comment how you fixed the cpu usage only issue?

**Comment by lqfarmer** [comment] 2017-09-07 14:53
@NickShahML ，I just update tensorflow to 1.3.0, and cudnn to version 6.0. Then, it works well.

**Comment by lqfarmer** [comment] 2017-09-07 14:54
@martinpopel , I fixed this issue as you said, but I still feel a bit of strange.

**Comment by martinpopel** [comment] 2017-09-07 15:18
> I fixed this issue as you said, but I still feel a bit of strange.

@lqfarmer: I don't understand. I suggested to close this issue (it is still open now) to keep the list of open issues tidy. The original problem you had (CPU only) is solved. The follow-up problem ("Number of ways to split" with multi-GPU training&evaluation) is still not solved, but there is another issue (#266) for this problem.

**Closed** 2017-09-10 05:11 UTC
