### ISSUE TITLE
How do I generate plain decoded text?

### ISSUE THREAD

**Issue by skyw** [tensorflow/tensor2tensor#357] opened 2017-10-12 22:48 UTC
It generates something like this, spaces and delimiters.
H a l l o   W e l t
G � � t e r v e r k e h r s w e l t

I remember decode used to generate plain text. How could I do that now?

**Comment by lukaszkaiser** [comment] 2017-10-13 00:37
This is very strange. It might be a bug or the model didn't train well? Did you re-train the model or are you loading an old checkpoint? Maybe some parameters changed?

**Comment by kelayamatoz** [comment] 2017-10-13 01:07
I observed the same thing when I was decoding. The pattern is that a space is added after every character in your text. Removing the extra space would give you the correct output.

**Comment by skyw** [comment] 2017-10-13 03:49
In decoding.py, it is like this
decoded_outputs = " ".join(map(str, outputs.flatten()))
This looks where the space comes from.

**Comment by fstahlberg** [comment] 2017-10-13 08:13
This is a duplicate of #333.

**Closed** 2017-11-13 22:59 UTC
