### ISSUE TITLE
batch_normalization does not work in t2t-pipeline

### ISSUE THREAD

**Issue by colmantse** [tensorflow/tensor2tensor#258] opened 2017-08-28 09:42 UTC
Hi all,

I have been able to reproduce the condition that cause the break. It is not possible to apply batch_norm if it is defined in a model_fn_body. Below is the minimum code for reproduction in the transformer's model_fn_body and the error log.
The batch_norm function works normal if I test it outside the architecture. It would be great to see if anyone is able to reproduce the error with the code and if someone got any insight on this matter. Many thanks!

This is the code for reproduction: 
```
def model_fn_body(self, features):
    hparams = self._hparams
    targets = features["targets"]
    inputs = features["inputs"]
    target_space = features["target_space_id"]

    inputs = common_layers.flatten4d3d(inputs)
    targets = common_layers.flatten4d3d(targets)

    #basically just the two lines below
    phase = True if hparams.mode == tf.contrib.learn.ModeKeys.TRAIN else False
    inputs = tf.contrib.layers.batch_norm(inputs,is_training=phase)

    (encoder_input, encoder_self_attention_bias,
     encoder_decoder_attention_bias) = (transformer.transformer_prepare_encoder(
         inputs, target_space, hparams))
    (decoder_input, decoder_self_attention_bias) = transformer.transformer_prepare_decoder(
        targets, hparams)

    encoder_input = tf.nn.dropout(
        encoder_input, 1.0 - hparams.layer_prepostprocess_dropout)
    decoder_input = tf.nn.dropout(
        decoder_input, 1.0 - hparams.layer_prepostprocess_dropout)
    encoder_output = transformer.transformer_encoder(
        encoder_input, encoder_self_attention_bias, hparams)

    decoder_output = transformer.transformer_decoder(
        decoder_input, encoder_output,
        decoder_self_attention_bias,
        encoder_decoder_attention_bias, hparams)
    decoder_output = tf.expand_dims(decoder_output, 2)

    return decoder_output
```
Error Log here:

```
Traceback (most recent call last):
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 87, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 83, in main
    schedule=FLAGS.schedule)
  File "l:\python34_colman\tensor2tensor\tensor2tensor\utils\trainer_utils.py", line 293, in run
    exp.train_and_evaluate()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 502, in train_and_evaluate
    self.train(delay_secs=0)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 280, in train
    hooks=self._train_monitors + extra_hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 677, in _call_train
    monitors=hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 296, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 458, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 958, in _train_model
    model_fn_ops = self._get_train_ops(features, labels)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 1165, in _get_train_ops
    return self._call_model_fn(features, labels, model_fn_lib.ModeKeys.TRAIN)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 1136, in _call_model_fn
    model_fn_results = self._model_fn(features, labels, **kwargs)
  File "l:\python34_colman\tensor2tensor\tensor2tensor\utils\model_builder.py", line 227, in model_fn
    len(my_hp.problems) - 1)
  File "l:\python34_colman\tensor2tensor\tensor2tensor\utils\input_fn_builder.py", line 196, in cond_on_index
    return fn(cur_idx)
  File "l:\python34_colman\tensor2tensor\tensor2tensor\utils\model_builder.py", line 200, in nth_model
    features, skip=(skipping_is_on and skip_this_one))
  File "l:\python34_colman\tensor2tensor\tensor2tensor\utils\t2t_model.py", line 474, in model_fn
    transformed_features)
  File "l:\python34_colman\tensor2tensor\tensor2tensor\utils\t2t_model.py", line 527, in model_fn_body_sharded
    datashard_to_features)
  File "l:\python34_colman\tensor2tensor\tensor2tensor\utils\expert_utils.py", line 191, in _call_
    outputs.append(fns[i](*my_args[i], **my_kwargs[i]))
  File "l:\python34_colman\tensor2tensor\tensor2tensor\utils\t2t_model.py", line 40, in fn_with_timing
    res = fn(*args, **kwargs)
  File "L:/python34_colman/projects/trans/usr\t2t_usr\cbhgtransformer.py", line 51, in model_fn_body
    inputs = tf.contrib.layers.batch_norm(inputs,is_training=phase)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 634, in batch_norm
    outputs = layer.apply(inputs, training=is_training)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\layers\base.py", line 503, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\layers\base.py", line 450, in _call_
    outputs = self.call(inputs, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\layers\normalization.py", line 397, in call
    self.moving_mean, new_mean, decay, zero_debias=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\moving_averages.py", line 73, in assign_moving_average
    return state_ops.assign_sub(variable, update_delta, name=scope)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\state_ops.py", line 215, in assign_sub
    return ref.assign_sub(value)
AttributeError: 'Tensor' object has no attribute 'assign_sub'
```

**Comment by rsepassi** [comment] 2017-08-29 03:19
(Repeating some info from the mailing list)

The issue is some bad interaction between batch_norm and the custom variable getter used in Tensor2Tensor (defined in expert_utils.py). 

We may need to fix that variable getter or possibly define our own version of batch norm in common_layers that works with the custom getter.

**Comment by colmantse** [comment] 2017-08-30 11:29
Dear all, 

I ran it with my old gtx 650, it is with tensor2tensor 1.2.1, tensorflow 1.3.0 and python 3.5.4. It manages to run until memory crash. However when I run it again with my gtx 1080 ti, with tensor2tensor 1.2.1, tensorflow 1.3.0 and python 3.6. the attributeError on top persists. 

Maybe the above issue has to do with python3.6?

below is the log of python 3.5.4. crash due to out of memory:

```
Traceback (most recent call last):
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1306, in _run_fn
    status, run_metadata)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : m=3402, n=384, k=128
         [[Node: body/model/parallel_0/body/decoder/layer_0/self_attention/multihead_attention/qkv_transform_single/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](body/model/parallel_0/body/decoder/layer_0/self_attention/multihead_attention/ExpandDims, Identity_105)]]
         [[Node: body/model/parallel_0/body/decoder/layer_0/ffn/conv_hidden_relu/sub_1/_3277 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_16199_body/model/parallel_0/body/decoder/layer_0/ffn/conv_hidden_relu/sub_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 87, in <module>
    tf.app.run()
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 83, in main
    schedule=FLAGS.schedule)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\utils\trainer_utils.py", line 301, in run
    exp.train_and_evaluate()
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 502, in train_and_evaluate
    self.train(delay_secs=0)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 280, in train
    hooks=self._train_monitors + extra_hooks)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 677, in _call_train
    monitors=hooks)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\util\deprecation.py", line 296, in new_func
    return func(*args, **kwargs)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 458, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 1010, in _train_model
    _, loss = mon_sess.run([model_fn_ops.train_op, model_fn_ops.loss])
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\monitored_session.py", line 518, in run
    run_metadata=run_metadata)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\monitored_session.py", line 862, in run
    run_metadata=run_metadata)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\monitored_session.py", line 818, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\monitored_session.py", line 972, in run
    run_metadata=run_metadata)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\monitored_session.py", line 818, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    options, run_metadata)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : m=3402, n=384, k=128
         [[Node: body/model/parallel_0/body/decoder/layer_0/self_attention/multihead_attention/qkv_transform_single/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](body/model/parallel_0/body/decoder/layer_0/self_attention/multihead_attention/ExpandDims, Identity_105)]]
         [[Node: body/model/parallel_0/body/decoder/layer_0/ffn/conv_hidden_relu/sub_1/_3277 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_16199_body/model/parallel_0/body/decoder/layer_0/ffn/conv_hidden_relu/sub_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'body/model/parallel_0/body/decoder/layer_0/self_attention/multihead_attention/qkv_transform_single/convolution', defined at:
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 87, in <module>
    tf.app.run()
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "L:/python34_colman/tensor2tensor/tensor2tensor/bin/t2t-trainer", line 83, in main
    schedule=FLAGS.schedule)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\utils\trainer_utils.py", line 301, in run
    exp.train_and_evaluate()
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 502, in train_and_evaluate
    self.train(delay_secs=0)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 280, in train
    hooks=self._train_monitors + extra_hooks)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 677, in _call_train
    monitors=hooks)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\util\deprecation.py", line 296, in new_func
    return func(*args, **kwargs)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 458, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 958, in _train_model
    model_fn_ops = self._get_train_ops(features, labels)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 1165, in _get_train_ops
    return self._call_model_fn(features, labels, model_fn_lib.ModeKeys.TRAIN)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 1136, in _call_model_fn
    model_fn_results = self._model_fn(features, labels, **kwargs)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\utils\model_builder.py", line 273, in model_fn
    len(my_hp.problems) - 1)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\utils\input_fn_builder.py", line 200, in cond_on_index
    return fn(cur_idx)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\utils\model_builder.py", line 242, in nth_model
    features, skip=(skipping_is_on and skip_this_one))
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\utils\t2t_model.py", line 474, in model_fn
    transformed_features)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\utils\t2t_model.py", line 527, in model_fn_body_sharded
    datashard_to_features)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\utils\expert_utils.py", line 191, in __call__
    outputs.append(fns[i](*my_args[i], **my_kwargs[i]))
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\utils\t2t_model.py", line 40, in fn_with_timing
    res = fn(*args, **kwargs)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\models\transformer.py", line 67, in model_fn_body
    encoder_decoder_attention_bias, hparams)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\models\transformer.py", line 244, in transformer_decoder
    hparams.hidden_size, hparams.num_heads, hparams.attention_dropout)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\layers\common_attention.py", line 813, in multihead_attention
    q_padding, kv_padding)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\layers\common_attention.py", line 713, in compute_qkv
    name="qkv_transform")
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\layers\common_layers.py", line 382, in conv1d
    **kwargs), 2)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\layers\common_layers.py", line 373, in conv
    **kwargs)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\layers\common_layers.py", line 363, in conv_internal
    return conv2d_kernel(kernel_size, "single")
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor2tensor\layers\common_layers.py", line 356, in conv2d_kernel
    result = conv_fn(inputs, filters, kernel_size_arg, name=name, **kwargs)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\layers\convolutional.py", line 551, in conv2d
    return layer.apply(inputs)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\layers\base.py", line 503, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\layers\base.py", line 450, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\layers\convolutional.py", line 158, in call
    data_format=utils.convert_data_format(self.data_format, self.rank + 2))
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 672, in convolution
    op=op)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 338, in with_space_to_batch
    return op(input, num_spatial_dims, padding)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 664, in op
    name=name)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 131, in _non_atrous_convolution
    name=name)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 397, in conv2d
    data_format=data_format, name=name)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\admen\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): Blas SGEMM launch failed : m=3402, n=384, k=128
         [[Node: body/model/parallel_0/body/decoder/layer_0/self_attention/multihead_attention/qkv_transform_single/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](body/model/parallel_0/body/decoder/layer_0/self_attention/multihead_attention/ExpandDims, Identity_105)]]
         [[Node: body/model/parallel_0/body/decoder/layer_0/ffn/conv_hidden_relu/sub_1/_3277 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_16199_body/model/parallel_0/body/decoder/layer_0/ffn/conv_hidden_relu/sub_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```

**Comment by colmantse** [comment] 2017-08-31 02:21
updates: I set custom getter as None and is now working. It is definitely the custom getter that is not working however I am not able to locate the cause.

**Comment by colmantse** [comment] 2017-10-31 16:44
@rsepassi I just find out using t2t.layers.apply_norm('batch') actually works. But it is not very clear how does it recognize training instances as the code seems to not have specified.

**Comment by rsepassi** [comment] 2017-11-14 00:27
Batch norm should now work in v1.2.8. 
(though there's a known bug with multi-gpu that will be fixed in the next release)

**Closed by rsepassi** 2017-11-14 00:27 UTC

**Comment by colmantse** [comment] 2017-11-22 15:28
It turns out it does not work in v1.2.9, could you confirm? 
Many thanks!

`Traceback (most recent call last):
  File "D:/projects/trans/bin/t2t-trainer", line 101, in <module>
    tf.app.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 129, in run
    _sys.exit(main(argv))
  File "D:/projects/trans/bin/t2t-trainer", line 97, in main
    schedule=FLAGS.schedule)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\trainer_utils.py", line 386, in run
    hparams=hparams)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\learn_runner.py", line 218, in run
    return _execute_schedule(experiment, schedule)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\learn_runner.py", line 46, in _execute_schedule
    return task()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 625, in train_and_evaluate
    self.train(delay_secs=0)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 367, in train
    hooks=self._train_monitors + extra_hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 807, in _call_train
    hooks=hooks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\estimator\estimator.py", line 313, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\estimator\estimator.py", line 729, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\estimator\estimator.py", line 713, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\model_builder.py", line 334, in wrapping_model_fn
    return model_fn(model, features, mode, hparams, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\model_builder.py", line 163, in model_fn
    max_idx=len(hparams.problems) - 1)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\input_fn_builder.py", line 182, in cond_on_index
    return fn(cur_idx)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\model_builder.py", line 131, in nth_model
    features, skip=(skipping_is_on and skip_this_one))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\t2t_model.py", line 578, in model_fn
    transformed_features)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\t2t_model.py", line 684, in model_fn_body_sharded
    datashard_to_features)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\expert_utils.py", line 244, in __call__
    outputs.append(fns[i](*my_args[i], **my_kwargs[i]))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensor2tensor\utils\t2t_model.py", line 42, in fn_with_timing
    res = fn(*args, **kwargs)
  File "D:/projects/trans/usr\t2t_usr\transformer_aug.py", line 49, in model_fn_body
    inputs=tf.nn.dropout(forenetwork(inputs,hparams), hparams.layer_prepostprocess_dropout)
  File "D:/projects/trans/usr\t2t_usr\transformer_aug.py", line 274, in forenetwork
    return cbhg(inputs,hparams)
  File "D:/projects/trans/usr\t2t_usr\transformer_aug.py", line 230, in cbhg
    h2 = tf.layers.batch_normalization(h1,training=phase)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\layers\normalization.py", line 770, in batch_normalization
    return layer.apply(inputs, training=training)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\layers\base.py", line 735, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\layers\base.py", line 625, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\layers\normalization.py", line 598, in call
    lambda: self.moving_mean)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\layers\utils.py", line 207, in smart_cond
    return fn1()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\layers\normalization.py", line 597, in <lambda>
    lambda: _do_update(self.moving_mean, new_mean),
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\layers\normalization.py", line 593, in _do_update
    var, value, self.momentum, zero_debias=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\moving_averages.py", line 88, in assign_moving_average
    return state_ops.assign_sub(variable, update_delta, name=scope)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\state_ops.py", line 217, in assign_sub
    return ref.assign_sub(value)
AttributeError: 'Tensor' object has no attribute 'assign_sub'`
